version: "3.9"

services:
  # Create service with Fiber sender.
  parsers-api:
    # env_file:
    #   - path: "./docker/docker-compose.env"
    #   - required: true
    container_name: parsers-api
    hostname: parsers-api-host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - rabbit

    environment:
      - AMQP_SERVER_URL=${AMQP_SERVER_URL}

    ports:
      - 3000:3000
    networks:
      - dev-network

  # Create service with RabbitMQ.
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    hostname: rabbit-host
    restart: always

    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq

    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    networks:
      - dev-network

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge
